apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: mern
spec:
  selector:
    role: frontend
  type: NodePort 
  ports:
    - name: frontend-port
      port: 3000
      protocol: TCP
      nodePort: 30006
