apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: mern
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: standard
  hostPath:
    path: /mnt/data