apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: db-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-database
      remoteRef:
        key: my-app-secret     # AWS Secrets Manager secret name
        property: db-database  # Key inside the secret JSON
    - secretKey: db-password
      remoteRef:
        key: my-app-secret
        property: db-password
