apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: mern
spec:
  selector:
    role: backend
  type: ClusterIP
  ports:
  - name: backend-port
    port: 80
    protocol: TCP
    targetPort: 3500